### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by olnor18** [vlinx-io/NativeImageAnalyzer#2]
This is an unknown encrypted binary without source code that supposedly requires internet - it is very likely malware! Please do not run without verifying the code yourself!
UPDATE: Author seems to use their own encryption tool, but IMO sourceless encrypted binaries have no place on Github and should not be trusted - do with this information as you wish

**Comment by vlinx-io** [comment]
Hi @olnor18 , we have stated in the README file, "due to the need to look up function names in the backend, Internet connection is required". 

Currently this is only a test project, we are not sure about the future development and planning of this project, so we do not open the source code at this stage, and since this project is written in Java, we encrypt it using Protector4J.

We don't have any need or incentive to write a malware. We are sorry for the misunderstanding.
